id: P004451
initial_creation_type: ocr
created_at: 28/03/2020
last_modified_at: 24/11/2021
source_metadata:
  id: bdr:W1KG9603
  title: ན་ལེནྡྲའི་བསྐང་གསོ།
  author: ''
  volumes:
    1eb1376a5ba74c079ef3ff3eb434e862:
      image_group_id: I1KG9629
      title: ''
      volume_number: 1
      total_pages: 332
      base_file: v001.txt
